package com.app;

import org.springframework.boot.Banner.Mode;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;

// we can also customized our Starter class ,like banner , logging etc .
// Text comes on console is called Banner 
// Banner is a interface in spring Boot having enum name Mode -
// we can off the banner and can also changed it 
// for change make banner.txt file under resources and write text , we can also use internet for designable text  


// we can count beans ( object ) generated by spring container using -
// 1- ac.getBeanDefinitionNames() : String[] 

// 2- using actuator endpoints  /beans

@SpringBootApplication
public class SpringBootStarterClassBannerGetAllBeansApplication {

	public static void main(String[] args) {
		SpringApplication s =new SpringApplication(SpringBootStarterClassBannerGetAllBeansApplication.class);

		// off the banner 
		// s.setBannerMode(Mode.OFF);

		// print on console 
		s.setBannerMode(Mode.CONSOLE);


		ConfigurableApplicationContext ac =	s.run(args);

		String [] beans = ac.getBeanDefinitionNames();
	
		for(String b:beans) {			
			System.out.println(b);
		}
		
		System.out.println("length is "+ac.getBeanDefinitionCount());

	}

}
